name: Lerna Pre-Release - 00
run-name: Lerna Pre-Release - 00 - Create status comment

on:
  workflow_call:
    inputs:
      prRef:
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true

jobs:
  create-status-comment:
    runs-on: ubuntu-latest
    outputs:
      comment_id: ${{ steps.status_comment.outputs.comment_id }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
          ref: ${{ inputs.prRef }}

      - name: Create status comment
        id: status_comment
        uses: actions/github-script@v7
        with:
          script: >
            github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: `> [!WARNING]
              > Pre-Release process initiated
            
              The pre-release is currently being created. No action is required on your part; this comment will automatically update once everything is complete.
              `
            }).then(response => {
              core.setOutput("comment_id", response.data.id)
            });