name: Preview publish package - 03
run-name: Preview publish package - 03 - Update status comment on failure

on:
  workflow_call:
    inputs:
      prRef:
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true

jobs:
  update-status-comment-on-failure:
    name: Update status pre-release comment on failure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          path: ./

      - name: Read artifacts
        run: |
          echo "comment_id=$(cat ./comment-artifact/comment_id.txt)" >> $GITHUB_ENV

      - name: Update status comment on failure
        uses: actions/github-script@v7
        with:
          script: |
            const comment_id = ${{ env.comment_id }}

            github.rest.issues.updateComment({
              ...context.repo,
              comment_id: comment_id,
              body: `
            > [!CAUTION]
            > Pre-Release failed
              `
            });