name: Lerna Pre-Release - 01
run-name: Lerna Pre-Release - 01 - Publish pre-release

on:
  workflow_call:
    inputs:
      prRef:
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true
      GIT_USER_NAME:
        required: true
      GIT_USER_EMAIL:
        required: true

jobs:
  publish-prerelease:
    name: Publish Prerelease to NPM
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.lerna_prerelease.outputs.changelog }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
          ref: ${{ inputs.prRef }}

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Configure Git
        run: |
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"

      - name: GitHub Package Registry Identity
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" > .npmrc
          echo "@exile-watch:registry=https://npm.pkg.github.com/" >> .npmrc

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Lerna publish pre-release
        id: publish-prerelease
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npx lerna version prerelease --preid preview --yes --no-push
          npx lerna publish from-git --dist-tag next --yes
          echo "changelog=$(npx lerna changed --json | tr '\n' ' ')" >> $GITHUB_OUTPUT

  create-prerelease-changelog-artifact:
    needs: publish-prerelease
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Write changelog to a file
        run: echo "${{ needs.publish-prerelease.outputs.changelog }}" >> changelog.txt

      - name: Upload changelog as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: changelog-artifact
          path: changelog.txt
          retention-days: 1
