name: Preview publish package - 04
run-name: Preview publish package - 04 - Remove preview-publish label

on:
  workflow_call:
    inputs:
      prRef:
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true

jobs:
  remove-preview-publish-label:
    name: Remove preview-publish label
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Remove preview-publish label
        uses: actions/github-script@v7
        with:
          script: |
            const labelToRemove = 'preview-publish'

            // Check if the PR already has the label
            const { data: labels } = await github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const hasLabel = labels.some(label => label.name === labelToRemove);

            if(!hasLabel) return;

            github.rest.issues.removeLabel({
              ...context.repo,
              issue_number: context.issue.number,
              name: [labelToRemove]
            });